Module5 task2
htmlacademy-yii/241239-task-force-1 pull request #10
Opened 2020-09-29 13:11 UTC by htmlviktor

2020-09-29 14:42 UTC, frexin requested changes

2020-09-29 14:42 UTC, frexin commented on frontend/controllers/TasksController.php
> +        $tasks = Task::find()->where(['status' => 'Новое'])->all();
Выдели статусы заданий в отдельную таблицу и сделай с ней связь.

2020-09-29 14:42 UTC, frexin commented on frontend/views/tasks/index.php
> +                                <a href="#" class="link-regular"><h2><?= isset($task->name) ? $task->name : "" ?></h2></a>
Все эти isset проверки не нужны: у модели $task всегда есть поля, их не может не быть

2020-09-29 14:42 UTC, frexin commented on frontend/views/tasks/index.php
> +                                <?= isset($task->description) ? $task->description : "" ?>
Здесь и в других местах: https://up.htmlacademy.ru/yii/1/criteries#b28

2020-09-29 14:42 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <span class="new-task__time">4 часа назад</span>
Время надо выводить

2020-09-29 14:42 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= $task->city->city ?></p>
Если у задачи нет привязки к городу, то будет ошибка

2020-09-29 14:42 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= $task->city->city ?></p>
И, кстати, убери ограничение not null с поля city_id

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +                    <span>17 заданий</span>
Эти значения надо из базы показывать

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +                    <?php for ($i = 0; $i < 5; $i++): ?>
Логику показа разметки рейтинга лучше вынести в какой нибудь хелпер

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +                    <p class="user__search-content">
Здесь должно быть "био"

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +                    <p class="link-name"><a href="#" class="link-regular"><?=$user->name . ' ' . $user->surname ?></a></p>
Не забываем про экранирование

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +                <span class="new-task__time">Был на сайте 25 минут назад</span>
Брать из БД

2020-09-29 14:42 UTC, frexin commented on frontend/views/users/index.php
> +            <div class="link-specialization user__search-link--bottom">
Брать из БД

2020-10-04 14:15 UTC, frexin requested changes

2020-10-04 14:15 UTC, frexin commented on console/migrations/m201003_152455_two.php
> +        $this->addColumn('user_info', 'bio', $this->text()->defaultValue('Some bio text'));
` Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'bio' can't have a default value`

2020-10-04 14:15 UTC, frexin commented on frontend/views/tasks/index.php
> +                                <a  class="new-task__type link-regular" href="#"><p><?= strip_tags($task->category->name); ?></p></a>
Имя категории не надо экранировать - это не является данными от пользователя

2020-10-04 14:15 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <div class="new-task__icon new-task__icon--<?= strip_tags($task->category->icon); ?>"></div>
Иконку категории не надо экранировать - это не является данными от пользователя

2020-10-04 14:15 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= strip_tags($task->city->city); ?></p>
Название города не надо экранировать - это не является данными от пользователя

2020-10-04 14:15 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= strip_tags($task->city->city); ?></p>
Ты также не исправил прошлые замечания, которые касались обязательности города

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                    <span><?= count($user->tasks0); ?> заданий</span>
`tasks0` - неудачное название для этой связи

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                    <span><?= count($user->reviews); ?> отзывов</span>
С числом заданий и отзывов лучше написать отдельные методы у модели пользователя, которые будут брать соответствующие связи и добавлять к ним `count()`. Это будет куда оптимальнее, чем извлекать все задания и отзывы для пользователя, только чтобы посчитать их количество
https://www.yiiframework.com/doc/api/2.0/yii-db-query#count()-detail

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                    <?php for ($i = 0; $i < 5; $i++): ?>
Так и не сделал хелпер

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                    <p class="link-name"><a href="#" class="link-regular"><?=$user->userInfos->name . ' ' . $user->userInfos->surname ?></a></p>
Имя/фамилию надо экранировать

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                <?php foreach ($user->userInfos->userCategories as $category): ?>
Сделай связь, которая сразу возвращает модели типа "Категория", вместо моделей типа "Привязка пользователей к категории".
https://www.yiiframework.com/doc/api/2.0/yii-db-activequery#viaTable()-detail

2020-10-04 14:15 UTC, frexin commented on frontend/views/users/index.php
> +                <span class="new-task__time">Был на сайте <?php echo Yii::$app->formatter->asRelativeTime($user->userInfos->edited_at, new DateTime("now")); ?></span>
Второй аргумент можно не указывать

2020-10-04 14:22 UTC, frexin commented
Чтобы добавить свой хелпер и обращаться к нему как к компоненту yii, то тебе понадобится:
1. Написать свой класс, реализующий всю необходимую логику и положить его, к примеру, в common/helpers/MyHelper.php
2. Зарегистрировать его в конфиге, в разделе components.

Подробнее здесь: https://www.yiiframework.com/doc/guide/2.0/ru/concept-service-locator

2020-10-04 14:23 UTC, frexin commented
Чтобы поменять локаль сайта, добавь это в frontend/config/main.php:
`'language' => 'ru'`

2020-10-06 14:26 UTC, htmlviktor commented on console/migrations/m201003_152455_two.php
> +        $this->addColumn('user_info', 'bio', $this->text()->defaultValue('Some bio text'));
Подробностей бы, от куда это. Я загружаю дамп, выполняю миграции и всё ок, никаких ошибок нигде не падает. https://prnt.sc/uu58wg

2020-10-06 14:30 UTC, htmlviktor commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= strip_tags($task->city->city); ?></p>
Экранирование поправил, ошибку понял. Не совсем врубился во второй момент, что именно нужно сделать? Я думал что город обязателен. Получается что город в task не обязателен чтобы задание выложить на биржу?

2020-10-06 14:34 UTC, frexin commented on console/migrations/m201003_152455_two.php
> +        $this->addColumn('user_info', 'bio', $this->text()->defaultValue('Some bio text'));
https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

> The BLOB, TEXT, GEOMETRY, and JSON data types cannot be assigned a default value.

2020-10-07 14:18 UTC, frexin approved these changes

2020-10-07 14:18 UTC, frexin commented on frontend/views/tasks/index.php
> +                            <p class="new-task__place"><?= $task->city->city; ?></p>
Распространенная ошибка. Попробуй удалить город у одной из задач и посмотри что будет

2020-10-07 14:18 UTC, merged