add task class
htmlacademy-yii/241239-task-force-1 pull request #2
Opened 2020-07-23 12:20 UTC by htmlviktor

При выполнении задания не понял несколько моментов, может ты прояснишь:

1. При попытке использовать - `spl_autoload_register()` а затем use, без include / require ничего не происходило. Может я неверно понял что-то.

2. Не вкурил работу assert, хотя и прочитал доку. Я рассчитывал что он выводить что-то будет в случае 'успеха' / 'не успеха'. Но он ничего не выводит + я пытался и echo выводить, короче ничего. 

Спасибо, буду ждать комментариев, верно ли я хоть понял задание. Создал кучу методов, не понял, верно ли я это сделал в общем, может переборщил?

2020-07-23 15:43 UTC, frexin requested changes

2020-07-23 15:43 UTC, frexin commented on src/Task.php
> +    public function getStatus($action)
Лучше переименовать, т.к. метод возвращает именно что следующий статус.

2020-07-23 15:43 UTC, frexin commented on src/Task.php
> +    const action_map = [
Константы всегда заглавными

2020-07-23 15:43 UTC, frexin commented on src/Task.php
> +        return self::status_map[$action];
Добавить проверку, что такое действие с таким именем существует среди доступных

2020-07-23 15:43 UTC, frexin commented on src/Task.php
> +        return self::action_map[$status];
Здесь должна быть более сложная логика. Дело в том, что действия будут разными для разных пользователей. Например, откликнуться на задание не может автор этого же задания, что логично. Именно поэтому мы передаем в класс id автора задания.

2020-07-23 15:43 UTC, frexin commented on src/Task.php
> +        $this->status = $status;
Надо проверить корректность имени статуса

2020-07-23 15:44 UTC, frexin commented
1. С автозагрузкой ты в целом поторопился - это будет в следующем задании
2. Попробуй добавить в начало сценария:
```assert_options(ASSERT_ACTIVE, 1);```

2020-07-24 16:38 UTC, htmlviktor commented
Попытался реализовать как понял. Перечитал тз, вроде всё понятно, но местами теряю картину целяком.

На всякий случай в Task добавил и РОЛИ, чтобы было проще работать с ними. Спасибо за ревью)

2020-07-25 14:21 UTC, merged