Module2 task1
htmlacademy-yii/241239-task-force-1 pull request #4
Opened 2020-08-17 17:16 UTC by htmlviktor

В общем, сделал как понимал. Думаю что явно есть неточности в архитектуре и том, как это должно в финале выглядеть. С классами было сложно в контексте - не понятно немного что за что будет отвечать. Как я понял из задания, нам нужно выделить классы-модели, которые будут в последствии работать с данными, в частности с БД как я понимаю. В общем, я выделил основные. И тут сразу момент, можно было бы дробить, по типу:

ProfileSettings, ProfilePortfolios и тд, так как у нас и в БД под это "многие к многим" можно было бы работать, но пока не стал усложнять, чтобы ты сказал, верно я хоть понял идею) Спасибо)

2020-08-18 14:29 UTC, frexin requested changes

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +CREATE DATABASE IF NOT EXISTS taskforce;
Пробовал свой дамп выполнять? Указывать кодировку БД необходимо внутри одной инструкции.

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +CREATE TABLE `users` (
Я бы добавил еще дату регистрации

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +	`email` varchar(255) UNIQUE,
Email и пароль должны быть not null

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +	`city_id` int(255) UNIQUE,
Город обязателен

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +	`skype` varchar(255) NOT NULL,
А вот скайп и telegram при регистрации не заполняются...

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +	`city_id` int(255) UNIQUE,
С ограничением unique на этом поле получится, что у тебя не может быть двух пользователей из одного города

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +CREATE TABLE `tasks` (
Я уже не буду описывать дальше каждый такой случай, но ты серьезно подумай об ограничениях not null для этой и других таблиц: у тебя они бывают стоят там, где не нужно, и отсутствуют где нужно

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +CREATE TABLE `profile_stats` (
Нужна ли эта таблица? Ведь здесь хранятся значения, которые всегда можно получить запросами из других таблиц?

2020-08-18 14:29 UTC, frexin commented on schema.sql
> +CREATE TABLE `task_feedbacks` (
Мне кажется, тебе не хватает таблицы для хранения отзывов о завершенных заданиях

2020-08-20 08:48 UTC, htmlviktor commented
Вроде всё что нужно поправил. Может где-то осталась какая-то мелочь и уже не вижу. В общем, в прошлый раз с этими not null был баг, там где они должны были быть, их не было, и наоборот. Не разобрался с чекбоксами в программе:)

2020-08-20 15:08 UTC, merged